name: static.z
# excludeDir: (optional) Regex pattern (in double quotes) or list of directories to exclude; .git and node_modules are always excluded
# match: (optional) Regex pattern or list of files to process; by default, common source files are included
# assets: (optional) List of relative file/directory paths to copy and mirror in the generated style guide

# theme:
#   logo: (optional) Filepath or URL of your logo
#   css: (optional) List of any CSS files to include in the <head> of the generated styleguide; see Theming section
#   js: (optional) List of any JS files to include in the <body> of the generated styleguide; see Theming section
#   sidebar:
#     background: (optional) Background of the sidebar; any valid CSS background property allowed, but hex colors must be quoted
#     textColor: (optional) Text color of the sidebar; any valid CSS color property allowed, but hex colors must be quoted

examples:
  #   css: (optional) List of any CSS files to include in the <head> of each rendered example
  #   js: (optional) List of any JS files to include in the <head> of each rendered example
  #   doctypeTag: (optional) HTML doctype to use for each rendered example; defaults to "<!doctype html>"
  #   htmlTag: (optional) <html> tag to use for each rendered example; defaults to "<html>"
  #   bodyTag: (optional) <body> tag to use for each rendered example; defaults to "<body>"
  headHtml: <meta name="viewport" content="width=device-width, initial-scale=1">
#   bodyHtml: (optional) HTML template of the example; the example's HTML content will be inserted in place of "{html}"

# webpackAppPath: For Webpack apps (esp. React, Angular, etc.), this is the `output.library` value in your webpack config
# emberAppName: For Ember apps, this is the name of the Ember app exported to the window object
#
# order: (optional) See Ordering section
